Revert "Added dirty hack to mitigate issues with ARM64 builds with GitHub Actions"
This reverts commit 9c372c89b563c95046c9896812cb3df259d317dd. It's nonsense. The ARM64 issues
appears before reaching the build script.

>Run ./extras/github/build-action
>Run docker/setup-buildx-action@v3
>Docker info
>Buildx version
>Inspecting default docker context
>Creating a new builder instance
Error: ERROR: failed to initialize builder builder-7cfe3cdd-acf8-4116-a011-40173ca3d469 (builder-7cfe3cdd-acf8-4116-a011-40173ca3d4690): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?